name: accemus
description: A CLI tool for fetching DSB/Untis substitution plans.
version: 1.0.0
homepage: https://github.com/Ampless/Accemus

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  dsbuntis: ^2.0.1
  schttp: ^1.0.0-nullsafety.0

dev_dependencies:
  pedantic: ^1.9.2
