name: accemus
description: A CLI tool for fetching DSB/Untis substitution plans.
version: 1.0.0
homepage: https://github.com/Ampless/Accemus

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  dsbuntis: ^1.0.0
  schttp: ^0.2.8

dev_dependencies:
  pedantic: ^1.9.2
