name: accemus
description: A CLI tool for fetching DSB/Untis substitution plans.
#version: 0.1.0
homepage: https://github.com/Ampless/Accemus

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  args: ^2.3.0
  dsbuntis: ^7.1.0

dev_dependencies:
  lints: ^1.0.1
