name: accemus
description: A CLI tool for fetching substitution plans from DSB/DSBMobile and
  parsing Untis HTML, as well as debugging dsbuntis.
version: 0.2.0-alpha.2
homepage: https://github.com/Ampless/Accemus

environment:
  sdk: '>=2.12.0 <3.0.0'

executables:
  accemus: accemus

dependencies:
  ansicolor: ^2.0.1
  args: ^2.3.0
  dsb: ^0.1.0-alpha.3
  dsbuntis: ^8.0.0-alpha.6
  hex: ^0.2.0
  highlight: ^0.7.0
  schttp: ^4.1.0

dev_dependencies:
  lints: ^1.0.1
